### ISSUE TITLE
Coming from a symlinked directory in a different shell can confuse the plugin

### ISSUE THREAD

**Issue by bedax** [externl/fish-symdir#10]
Try the following:

```
mkdir -p x/y
ln -s x/y z
bash # or sh
cd z
fish
```

You'll see now the current directory in the prompt is shown as `x/y` where it should be `z`. I don't find this to be a huge inconvenience, but I thought I'd report it in case you're interested.

Regardless, I really appreciate this plugin, thanks.

**Comment by externl** [comment]
Unfortunately I don't think anything can be done here. Fish is very strict about always using the real path for `PWD`. When Fish is started from Bash with a PWD that is a symlink it immediately resolves it.

A workaround would be to have bash export `symnav_pwd` and have bash update it to always match `PWD`.This away symnav will get the right directory when it's initialized.

**Comment by bedax** [comment]
ah fair enough, that seems like a lot of effort for something that happens rarely, at least for me. Plus it would only be a fix for bash and not sh or zsh or whatever else. thanks again, but I'll close this then.
