### ISSUE TITLE
problem if the home folder itself is a symbolic link

### ISSUE THREAD

**Issue by lapcchan** [externl/fish-symdir#4]
if the home folder itself is a symbolic link, when first login (prompt_pwd) won't shows the link.
any work around for it? add a "cd" on config.fish won't help.

also if i do a cd after login, (prompt_pwd) won't recognize the home folder as ~/ but shows the actually symbolic link path of home folder.

**Comment by externl** [comment]
> if the home folder itself is a symbolic link, when first login (prompt_pwd) won't shows the link.
any work around for it? add a "cd" on config.fish won't help.

Not sure what you mean by this.

> also if i do a cd after login, (prompt_pwd) won't recognize the home folder as ~/ but shows the actually symbolic link path of home folder.

I can reproduce this. Looking into fixing.

**Comment by lapcchan** [comment]
if the home folder of user abc is /home/abc (base on /etc/passwd), but /home/abc is actually is a  symbolic link  from /home2/abc.

when i first login with fish, it will shows /home2/abc if i put (prompt_pwd) on prompt, right after i do my first "cd" command, prompt will shows /home/abc

**Comment by externl** [comment]
I've pushed a fix that worked locally. Please try. You'll need to update and restart your shell.

**Comment by externl** [comment]
@lapcchan Do you have your own custom `fish_prompt` or `prompt_pwd`, are you using the builtin ones, or ones from some other place?

**Comment by lapcchan** [comment]
heres my prompt
```
function fish_prompt
  echo -n -s (set_color green) "$USER" @ (prompt_hostname) ' '
  set last_status $status

  set_color normal
  printf '%s' (prompt_pwd)

  set_color normal
  printf '%s ' (__fish_git_prompt)

  set_color normal
end
```

i've try the update, first login it will show the original path on prompt, after the first "cd", its back to normal as ~

**Comment by externl** [comment]
What is your `prompt_pwd`, just normal?

**Comment by externl** [comment]
In your `config.fish` can you add

```
echo $HOME
echo ~
functions prompt_pwd
```
and post the output.

Symnav doesn't initialize until the fist time you press enter or tab, so I'm surprised your original prompt does not work.

**Comment by lapcchan** [comment]
if i put those 2 echo before prompt_pwd it shows

```
/home/vince
/home2/vince
```

and yes when i just press enter, the prompt become normal and shows ~ instead of /home2/vince

**Comment by externl** [comment]
Please add the output of `functions prompt_pwd` as well called from `config.fish`

**Comment by lapcchan** [comment]
```
# Defined in /usr/share/fish/functions/prompt_pwd.fish @ line 1
function prompt_pwd --description 'Print the current working directory, shortened to fit the prompt'
	set -q argv[1]
    and switch $argv[1]
        case -h --help
            __fish_print_help prompt_pwd
            return 0
    end

    # This allows overriding fish_prompt_pwd_dir_length from the outside (global or universal) without leaking it
    set -q fish_prompt_pwd_dir_length
    or set -l fish_prompt_pwd_dir_length 1

    # Replace $HOME with "~"
    set realhome ~
    set -l tmp (string replace -r '^'"$realhome"'($|/)' '~$1' $PWD)

    if [ $fish_prompt_pwd_dir_length -eq 0 ]
        echo $tmp
    else
        # Shorten to at most $fish_prompt_pwd_dir_length characters per directory
        string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp
    end
end
```

**Comment by externl** [comment]
Hmm... since this happens before you press `cd` I'm not sure it's an issue with symnav. Can you try uninstalling symanv then seeing if your prompt says `~` or `/home2/vince`

**Comment by lapcchan** [comment]
it's fish's way to handle symbolic link. it's not a major issue anyway. just wondering if symnav can bring back the old style bash way to handle it.

**Comment by lapcchan** [comment]
and yes. uninstalled symnav my prompt still stay with /home2/vince, unless u change to bash.

**Comment by externl** [comment]
With symav disabled what do you get when you run:
```
set realhome ~
echo $PWD
echo $realhome
string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
```

**Comment by lapcchan** [comment]
```
 /home2/vince
 /home2/vince
 /home2/vince
```

**Comment by externl** [comment]
Odd, what's the output of `string replace -r '^'"/home2/vince"'($|/)' '~$1' /home2/vince`?

Edit: Since fish hasn't initialized yet you're seeing the default behavior. However, it really should be replacing `/home2/vince` with `~`. I don't see how that `string replace` could be failing.

**Comment by lapcchan** [comment]
the output if i just run it on fish
```
string replace -r '^'"/home2/vince"'($|/)' '~$1' /home2/vince
```

is ~

**Comment by externl** [comment]
Ok that's weird since the above bit didn't work.

**Comment by externl** [comment]
Can you try various combinations:
```
set realhome ~
echo PWD: $PWD
echo realhome: $realhome
string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
string replace -r '^'"$realhome"'($|/)' '~$1' /home2/vince
string replace -r '^'"/home2/vince"'($|/)' '~$1' $PWD
```

**Comment by lapcchan** [comment]
oh i think i know whats the problem. it's the problem of regex and string escape. 

since the symbolic link was too long so i truncate the result. i made a new login and test it, here's the actual result.

appended to config.fish
```
set realhome ~
echo PWD: $PWD
echo realhome: $realhome
string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
string replace -r '^'"$realhome"'($|/)' '~$1' /home2/^home^vince
string replace -r '^'"/home2/\^home\^vince"'($|/)' '~$1' $PWD
```
```
PWD: /home2/^home^vince
realhome: /home2/^home^vince
/home2/^home^vince
/home2/^home^vince
~
Welcome to fish, the friendly interactive shell
vince@test /home2/^home^vince
```

the problem actually was just the linked folder with `^`

**Comment by externl** [comment]
Cool. So the initial pre-symnav string replace is working now? If so and the other symnav issue is working correctly please close this issue.

**Comment by lapcchan** [comment]
it's still doesn't work, before the first `enter` or `cd` , for the your test code i escaped the ^ with \ on the last line.

**Comment by externl** [comment]
So your path has `^`'s in it?

**Comment by lapcchan** [comment]
yes the original path has ^

**Comment by externl** [comment]
Hm... I guess fish does not handle this well.

**Comment by externl** [comment]
You may be able to work around it by manually initializing symnav in `config.fish`. Try calling `__symnav_initialize`.

Edit: Make sure to put it at/near the end of `config.fish`.

**Comment by lapcchan** [comment]
yes it does work with `__symnav_initialize` at the end of config.fish.

however i see those 2 warning
```
 [symnav] execution bindings are not installed
 [symnav] completion bindings are not installed
```

no harm at all right? can i get rid of them?

**Comment by externl** [comment]
Yep, at this point user key bindings have not been loaded by fish.

Try `__symnav_initialize ^/dev/null`

**Comment by lapcchan** [comment]
`__symnav_initialize >/dev/null` works. thanks
