### ISSUE TITLE
running screen inside symbolic linked path

### ISSUE THREAD

**Issue by lapcchan** [externl/fish-symdir#7]
if i am inside any symbolic linked path, the prompt do shows the symbolic link. however once i run 'screen' the prompt will be translated to full path.

**Comment by externl** [comment]
Thanks for reporting. Seems to also happen with `tmux`.

**Comment by externl** [comment]
This should be fixed now. Please let me know if the update goes smoothly. I moved some files around and am not really sure how well fisherman will handle it.

**Comment by lapcchan** [comment]
after fisher update, shower those 2 errors after login
```
 symnav_initialize.fish: execution bindings are not installed
 symnav_initialize.fish: completion bindings are not installed
```

and screen still revert current prompt to original path.

**Comment by lapcchan** [comment]
same error after uninstall and reinstall via fisher.

**Comment by externl** [comment]
Thanks. I just pushed a fix to disable (they are incorrect in this case) these warnings until I fix it correctly.
