### ISSUE TITLE
Breaks `cd -`

### ISSUE THREAD

**Issue by admirabilis** [externl/fish-symdir#8]
Hello! Thanks for maintaining fish-symnav! It makes working with mc and fish much better!

The expected behaviour of `cd -`, [according to the documentation](https://fishshell.com/docs/current/commands.html#cd), is going back one directory:

```
$ cd /; and pwd
/
$ cd -; and pwd
/home/teresaejunior
```

But after installing `externl/fish-symnav`:

```
$ cd /; and pwd
/
$ cd -; and pwd
cd: The directory “//-” doesn't exist
```

**Comment by externl** [comment]
Thanks for reporting this issue, @teresaejunior.

**Comment by externl** [comment]
I don’t think this is too hard to fix, however I’m traveling until mid next week so I’m not sure when I’ll be able to get to it.

**Comment by admirabilis** [comment]
I have just done some tests and, with or without symnav, the expected behavior of `cd -` works exactly the same as `cd $dirprev[-1]`. Something like `if test $argv[1] = -; cd $dirprev[-1]; end` should be enough!

**Comment by admirabilis** [comment]
Meanwhile, have a good trip!

**Comment by externl** [comment]
Thanks! I pushed a quick fix for this (I think). Let me know if it works 😄.

**Comment by admirabilis** [comment]
It works! Thank you very much!
