### ISSUE TITLE
Unknown error trying to locate directory ""

### ISSUE THREAD

**Issue by heretoreportabug** [externl/fish-symdir#9]
Hello.
I've been using this tool for the past hour or so, and I'm pretty sure I found a bug when using `cd ..` 
Expected behavior:

    cd ~
    cd ..
    cd ..
Should result in the user being in the root directory.
Actual behavior:

    cd ~
    cd ..
    cd ..
    cd: Unknown error trying to locate directory ""
Results in the user remaining in `/home`. Once a user has run `cd /`, however, they can use `cd ..` to navigate back to the root directory _(Unless they run `cd $HOME` or `cd ~` after)_.

Additionally, once navigating to another directory after using `cd /`, the path always has a leading slash (e.g. `//home`)

Edit: running `cd ..` when in the root directory also results in the title's error message

**Comment by externl** [comment]
Thanks for reporting this issue @heretoreportabug. I'm traveling this week and not sure how much time I'll have to look at this until mid next week.

**Comment by externl** [comment]
This should be fixed now. Please reopen if it's not.
